name: C++ CI with Google Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Install GCC
        run: sudo apt-get install g++-12

      - name: Install Google Test dependencies
        run: sudo apt-get install libgtest-dev cmake

      - name: Build project and run ctest
        run: |
          mkdir build
          cd build
          cmake ..
          make
          echo "ctest report:"
          ctest --output-on-failure

      - name: Run Google Tests
        run: |
          cd build/test/bin
          for test_exe in $(find . -name "tests_week_*" -type f); do
            echo "Running test: $test_exe"
            $test_exe
          done


